
rem Clean up the results directory
rmdir /S /Q results
mkdir results

rem Synthesize the VHDL Wrapper Files


echo 'Synthesizing example design with XST';
xst -ifn xst.scr
copy RAM_WRITE_top.ngc .\results\


rem Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
copy ..\..\RAM_WRITE.ngc results\


rem  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
copy ..\example_design\RAM_WRITE_top.ucf results\

cd results

echo 'Running ngdbuild'
ngdbuild -p xc6vlx240t-ff1759-3 RAM_WRITE_top

echo 'Running map'
map RAM_WRITE_top -o mapped.ncd -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -sim -tm RAM_WRITE_top -pcf mapped.pcf -w -sdf_anno false routed.ncd routed.v
